export enum ProviderPermissionEnumModel {
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  SERVE = 'SERVE',
  UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS',
  ADD_SERVICE_PROVIDER = 'ADD_SERVICE_PROVIDER',
  OWNER = 'OWNER'
}
