-- Inserir Tipos de Serviço com Ícones Font Awesome
INSERT IGNORE INTO service_type (id, name, icon, created_at, updated_at, created_by, updated_by) VALUES
    (1, 'Beauty', 'spa', NOW(), NOW(), 'system', 'system'),
    (2, 'Fitness', 'dumbbell', NOW(), NOW(), 'system', 'system'),
    (3, 'Education', 'book', NOW(), NOW(), 'system', 'system'),
    (4, 'Home Services', 'house', NOW(), NOW(), 'system', 'system'),
    (5, 'Wellness', 'heart', NOW(), NOW(), 'system', 'system'),
    (6, 'Health', 'stethoscope', NOW(), NOW(), 'system', 'system'),
    (7, 'Finance', 'money-bill-wave', NOW(), NOW(), 'system', 'system'),
    (8, 'Legal', 'gavel', NOW(), NOW(), 'system', 'system'),
    (9, 'Technology', 'laptop-code', NOW(), NOW(), 'system', 'system'),
    (10, 'Transportation', 'car', NOW(), NOW(), 'system', 'system'),
    (11, 'Food Delivery', 'utensils', NOW(), NOW(), 'system', 'system'),
    (12, 'Cleaning', 'broom', NOW(), NOW(), 'system', 'system'),
    (13, 'Security', 'shield-alt', NOW(), NOW(), 'system', 'system'),
    (14, 'Photography', 'camera', NOW(), NOW(), 'system', 'system'),
    (15, 'Consulting', 'chalkboard-teacher', NOW(), NOW(), 'system', 'system'),
    (16, 'Event Planning', 'calendar-check', NOW(), NOW(), 'system', 'system'),
    (17, 'Pet Care', 'paw', NOW(), NOW(), 'system', 'system'),
    (18, 'Construction', 'hard-hat', NOW(), NOW(), 'system', 'system'),
    (19, 'Cleaning', 'spray-can', NOW(), NOW(), 'system', 'system'),
    (20, 'Entertainment', 'theater-masks', NOW(), NOW(), 'system', 'system'),
    (21, 'Marketing', 'bullhorn', NOW(), NOW(), 'system', 'system'),
    (22, 'Real Estate', 'building', NOW(), NOW(), 'system', 'system'),
    (23, 'Travel', 'plane', NOW(), NOW(), 'system', 'system'),
    (24, 'Design', 'paint-brush', NOW(), NOW(), 'system', 'system'),
    (25, 'Cleaning', 'vacuum', NOW(), NOW(), 'system', 'system'),
    (26, 'Tutoring', 'chalkboard', NOW(), NOW(), 'system', 'system'),
    (27, 'Massage', 'hands', NOW(), NOW(), 'system', 'system'),
    (28, 'Laundry', 'tshirt', NOW(), NOW(), 'system', 'system'),
    (29, 'Delivery', 'truck', NOW(), NOW(), 'system', 'system'),
    (30, 'Repair', 'wrench', NOW(), NOW(), 'system', 'system'),
    (31, 'Translation', 'language', NOW(), NOW(), 'system', 'system'),
    (32, 'Writing', 'pen', NOW(), NOW(), 'system', 'system'),
    (33, 'Gardening', 'seedling', NOW(), NOW(), 'system', 'system'),
    (34, 'Cleaning', 'soap', NOW(), NOW(), 'system', 'system'),
    (35, 'Cooking', 'blender', NOW(), NOW(), 'system', 'system'),
    (36, 'Tutoring', 'user-graduate', NOW(), NOW(), 'system', 'system'),
    (37, 'Cleaning', 'toilet-paper', NOW(), NOW(), 'system', 'system'),
    (38, 'Fitness', 'running', NOW(), NOW(), 'system', 'system'),
    (39, 'Beauty', 'cut', NOW(), NOW(), 'system', 'system'),
    (40, 'Home Services', 'tools', NOW(), NOW(), 'system', 'system');
