package com.academy.models.notification;

public enum NotificationTypeEnum {

    ADDED_TO_CART,
    REMOVED_FROM_CART,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    WARNING,
    APPROVED_SERVICE,
    REJECTED_SERVICE
}
